"""Fixed-radius Extraction: An Alternative to Boundary-Based Extraction.

Boundary-based extraction (in pipeline.py) asks OpenStreetMap for all data inside a named location's administrative boundary.

Administrative boundaries differ across countries. For example, 'City of London' represents approximately one square-mile, whereas 'Melbourne, Victoria,' is an entire metropolitan municipality. 
Therefore, cities extracted via this method cannot be compared spatially, nor can they be compared using any metrics dependent upon the size/characteristics of the area being analyzed.

This module performs a fixed radius extraction: A region of side length 2 x RADIUS_M centered about the geocoded city center. 
Thus, each city will contribute the same amount of space, making inter-city comparisons apples-to-apples.

There is also a practical advantage to performing a fixed radius extraction. 
It is much easier to resolve a place name to a single *point* than it is to resolve it to a *polygon*. 
As such, there are often names that do not have any polygon associated with their representation in the geocoding database that still geocode to a single coordinate. 
In addition, cities that could not be extracted based on their administrative boundary may sometimes be recoverable through fixed-radius methods.

Both methods are maintained side-by-side rather than having one replace the other. 
This design approach is used so that the results generated by both methods can be compared and justification provided for why a particular method was selected. """

from __future__ import annotations

import logging
from pathlib import Path

import networkx as nx
import osmnx as ox

from . import config
from .formats import write_graph
from .pipeline import consolidate, project, reduce_to_simple

log = logging.getLogger(__name__)

# Radius of the fixed-square area to extract. 
# Half width of the extracted square 5000m gives a 10km x 10km region, should provide sufficient coverage to capture the central business district and inner suburbs of most cities, 
# yet allow for timely extraction of all cities in the list. 
RADIUS_M = 5000

# Fixed-radius graphs will be stored adjacent to the boundary-based dataset, 
# thus allowing both to be retained for future reference and comparison. 
RADIUS_GRAPH_DIR = config.OUTPUT_DIR / "graphs_radius"


def geocode_centre(query: str) -> tuple:
    """Geocode a place name to determine its representative point coordinates (latitude,longitude). Geocoding resolves a place name to a *coordinate*, not a *polygon*. 
    The ability to geocode names without polygons makes this method successful when attempting to geocode names lacking polygons in the database. """
    return ox.geocode(query)


def download_radius(centre: tuple, radius_m: int = RADIUS_M) -> nx.MultiDiGraph:
    """Downloads the accessible road network within a specified radius of a specific point. 
    When requesting the network (dist_type="bbox") request a *bounding box* of width 2*radius_m meters around the point specified in centre (not a radius in terms of network distance). 
    The reason for specifying a *bounding box* is due to our desire for the area of the extracted space to be uniform for each city. 
    Network-distance areas would vary depending on the density of roads surrounding the extraction point. """
    return ox.graph_from_point(
        centre,
        dist=radius_m,
        dist_type="bbox",
        network_type=config.NETWORK_TYPE,
        simplify=True,
        retain_all=False,
    )


def process_city_radius(name: str, query: str, radius_m: int = RADIUS_M,
                        output_dir: Path | None = None) -> dict:
    """Process a single city through the fixed-radius extraction process and return the record produced during processing. 
    Stage 2-5 of the boundary-extraction process (project, consolidate, reduce, and export) were copied directly into this fixed-radius process. 
    Thus, the primary distinction between the two data sets occurs at stage 1 where the boundary-extracted process uses an administrative boundary 
    for extraction vs. this process using a fixed radius extraction. This was done intentionally. 
    By doing so, any differences found between the two data sets will be attributed to differences in the extraction area as opposed to differences in downstream processing. """
    output_dir = Path(output_dir or RADIUS_GRAPH_DIR)
    slug = name.lower().replace(" ", "_").replace(",", "")

    centre = geocode_centre(query)
    log.info("centre for %s: %.5f, %.5f", name, centre[0], centre[1])

    raw = download_radius(centre, radius_m)
    raw_nodes = raw.number_of_nodes()

    projected = project(raw)
    crs = str(projected.graph.get("crs"))

    consolidated = consolidate(projected)
    simple = reduce_to_simple(consolidated)

    path = write_graph(simple, output_dir / f"{slug}.txt", config.COORD_PRECISION)

    return {
        "city": name,
        "query": query,
        "centre_lat": round(centre[0], 5),
        "centre_lon": round(centre[1], 5),
        "radius_m": radius_m,
        "crs": crs,
        "raw_nodes": raw_nodes,
        "final_nodes": simple.number_of_nodes(),
        "final_edges": simple.number_of_edges(),
        "reduction_pct": round(100 * (1 - simple.number_of_nodes() / raw_nodes), 1)
        if raw_nodes
        else 0.0,
        "file": str(path.relative_to(config.PROJECT_ROOT)),
    }
